---
title: "Reproducible Research: Peer Assessment 1"
author: "Mano Yakandawala"
output: 
  html_document:
    keep_md: true
---
#### Report created on : `r format(Sys.time(), "%a %b %d %Y")`

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
```

## Loading and preprocessing the data
```{r LoadData}
#Read the data.
alldata = read.csv("activity.csv")
#we want to group the data by date and the summarise by date to get the count
ProData =  alldata %>% group_by(date) %>%
        summarise(total = sum(steps))
```

## What is mean total number of steps taken per day?
```{r MeanTotal}
ggplot(ProData, aes(x=date, y=total)) + 
        geom_bar(stat="identity", color="black", fill="wheat") + 
        labs(x="Date", y="Total Steps", title="Total Steps per Day")

ggsave("figures/TotalStepsPerDay.png")

summary(ProData)

mean(ProData$total, na.rm = TRUE) #Mean Steps Taken.
median(ProData$total, na.rm = TRUE) #Median Steps Taken.
```

## What is the average daily activity pattern?
```{r MeanTotal2}
AvgDailyData =  na.omit(alldata %>% group_by(interval))  %>%
        summarise(averageSteps = mean(steps))

ggplot(AvgDailyData, aes(x=interval, y=averageSteps)) + 
        geom_line() + 
        labs(x="Time Interval", y="Average Steps", title="Average Steps per Time Interval of 5 mins")

ggsave("figures/AverageStepsPerTimeInterval.png")

AvgDailyData[which.max(AvgDailyData$averageSteps),]
```

## Imputing missing values
```{r MissingValues}
#total number of missing values..
nrow(alldata[!complete.cases(alldata),])

#strategy - fill the interval mean if data is missing for an interval
MissingData =  alldata %>% group_by(interval) %>%
        mutate(steps = ifelse(is.na(steps), mean(steps, na.rm = TRUE), steps))

#this dataset will be used later
CompleteSet = MissingData 

MissingData =  MissingData %>% 
        ungroup() %>%
        group_by(date) %>%
        summarise(total = sum(steps))

```

```{r ImputeData}
ggplot(MissingData, aes(x=date, y=total)) + 
        geom_bar(stat="identity", color="black", fill="wheat") + 
        labs(x="Date", y="Total Steps", title="Total Steps per Day with Imputed Data")

ggsave("figures/TotalStepsPerDayWithImputedData.png")

summary(MissingData)

mean(MissingData$total, na.rm = TRUE) #Mean Steps Taken.
median(MissingData$total, na.rm = TRUE) #Median Steps Taken.
```

## Are there differences in activity patterns between weekdays and weekends?
```{r Weekdata}
WeekData =  CompleteSet %>% 
        ungroup() %>%
        mutate(day=ifelse(weekdays(as.Date(date)) %like% ("S"),
                          "Weekend"," Weekday")) %>%
        group_by(day, interval)  %>%
        summarise(averageSteps = mean(steps))

ggplot(WeekData, aes(x=interval, y=averageSteps, fill=day)) + 
        geom_line() + 
        facet_grid(day ~ .) + 
        labs(x="Time Interval", y="Average Steps", title="Average Steps per Time Interval of 5 mins")

ggsave("figures/TotalStepsByIntervalandWeekdays.png")
```

#https://github.com/sefakilic/coursera-repdata/blob/master/project1/PA1_template.Rmd
